personal_portfolio-project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.detail, name="detail"),
]


personal_portfolio-project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views



urlpatterns = [
    path('', views.portfolio, name="portfolio"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('skils/', views.skils, name="skils"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio-project/blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    dataTime = models.DateTimeField()
    discription = models.TextField()
    
    def __str__(self):
        return self.title

personal_portfolio-project/portfolio/models.py
from django.db import models

class Project(models.Model):
    image = models.ImageField(upload_to="portfolio/images/")
    title = models.CharField(max_length=100)
    discription = models.CharField(max_length=250)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio-project/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-dataTime')[:5]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

personal_portfolio-project/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def portfolio(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/portfolio.html', {'projects':projects})

def skils(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/skils.html', {'projects':projects})

personal_portfolio-project/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}

<section class="home">
    <div class="home-content">
        <h3>A Little Bit</h3>
        <h1>About Yourself</h1>
        <br>
        <p>Participated in the creation of the official website for
            <br>the college based on WordPress.
        </p>
        <br>
        <p>Launched a website online connected a domain. (First experience)<br>
            Set up a Linux-based server and cash register equipment for a grocery store</p>
        <br>
        <h3>Part-time Job</h3>
        <p>At the moment I understand the possibilities of the Django framework.
            <br>Hobby: I am fond of design in the genre of illustrations.
            Detailing (professional car wash)
        </p>
        <div class="home-sci">
            <a href="https://vk.com/m.malkov2013" style="--i:7"><i class='bx bxl-vk'></i></a>
            <a href="https://t.me/Max_Mal20" style="--i:8"><i class='bx bxl-telegram'></i></a>
            <a href="mailto:m.malckov2013@yandex.ru" style="--i:9"><i class='bx bxl-gmail'></i></a>
            <a href="{% static 'portfolio/Resume.pdf' %}" style="--i:10"><i class='bx bxs-save'></i></a>
        </div>
    </div>
</section>

{% endblock %}

personal_portfolio-project/portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatioble" content="IE=edge">
  <link rel="stylesheet" href="{% static 'portfolio/custom.css' %}">
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  <title>Max Malkov</title>
  <link rel="icon" type="image/png" href="{% static 'portfolio/Logo2.png' %}">
  <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
</head>

<body>
  <header class="header">
    <a href="#" class="logo">Portfolio</a>
    <nav class="navbar">
      <a href="{% url 'portfolio' %}" style="--i:1" class="active">Home</a>
      <a href="{% url 'blog:all_blogs' %}" style="--i:2">About</a>
      <a href="{% url 'skils' %}" style="--i:3">Skill</a>
      <a href="{% static 'portfolio/Resume.pdf' %}" style="--i:4">Resume</a>
    </nav>
  </header>
  <div>
    <div>
      {% block content %}{% endblock %}
    </div>
  </div>

   
</body>

</html>

personal_portfolio-project/portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}

<section class="home">
    <div class="home-content">
      <h3>Hello, It`s Me</h3>
      <h1>Max Malkov</h1>
      <h3>And I`m a <span class="text"></span></h3>
      <p>I am a simple guy from the outback of our vast country,
        <br>who wants to succeed in this world and reach certain heights.</p>
        <div class="home-sci">
          <a href="https://vk.com/m.malkov2013" style="--i:7"><i class='bx bxl-vk' ></i></a>
          <a href="https://t.me/Max_Mal20" style="--i:8"><i class='bx bxl-telegram' ></i></a>
          <a href="mailto:m.malckov2013@yandex.ru" style="--i:9"><i class='bx bxl-gmail' ></i></a>
          <a href="{% static 'portfolio/Resume.pdf' %}" style="--i:10"><i class='bx bxs-save'></i></a>
        </div>
        <a href="{% url 'blog:all_blogs' %}" class="bth-box">More About Me</a>
    </div>

  </section>
  <script src="{% static 'portfolio/main.js' %}"></script>

{% endblock %}

personal_portfolio-project/portfolio/templates/portfolio/skils.html
{% extends 'portfolio/base.html' %}
{% block content %}
{% load static %}

<section class="homeFons">
    <div class="home-content">
        <h3>A Little about My</h3>
        <h1>SKILS</h1>
        <h3>Programming languages</h3> 
        <p>CSharp, Python, JavaScript,<br> 
            Basics of Java, Kotlin
        </p>
        <br>
        <h3>Real world languages</h3>
        <br>
        <p>Russian(native), English(A2), Garman(A1)</p>
        <div class="home-sci">
            <a href="https://vk.com/m.malkov2013" style="--i:7"><i class='bx bxl-vk' ></i></a>
            <a href="https://t.me/Max_Mal20" style="--i:8"><i class='bx bxl-telegram' ></i></a>
            <a href="mailto:m.malckov2013@yandex.ru" style="--i:9"><i class='bx bxl-gmail' ></i></a>
            <a href="{% static 'portfolio/Resume.pdf' %}" style="--i:10"><i class='bx bxs-save'></i></a>
          </div>
    </div>
    
</section>

{% endblock %}